export const committees = [
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
  {
    img: "/img/memberimg.png",
    shortName: "nickname",
    name: "name",
    excerpt: "excerpt",
    description: "description",
    guide: "/",
  },
];
