import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import NewNavbar from "./components/Navbar";
import Footer from "./components/footer";
import Provider from "./components/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DelTech MUN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <NewNavbar></NewNavbar>
          {children}
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
